"""Central configuration — single source of truth for all settings."""

from pathlib import Path

# LLM Models
MODELS = {
    "heavy_logic": "openai/gpt-oss-120b",
    "quantitative": "qwen/qwen3-32b",
    "orchestrator": "moonshotai/kimi-k2-instruct-0905",
    "language": "llama-3.3-70b-versatile",
    "fast": "llama-3.1-8b-instant",
}

# Resilience: Cascading Fallback Chain for Rate Limits / Missing Models
MODEL_FALLBACK_CHAIN = [
    MODELS["heavy_logic"],
    MODELS["language"],
    MODELS["quantitative"],
    MODELS["orchestrator"],
    MODELS["fast"],
]

# Agent intent keywords
INTENT_KEYWORDS = {
    "pricing": ["price", "pricing", "margin", "discount", "revenue",
                "competitor", "elasticity"],
    "churn": ["churn", "attrition", "satisfaction", "retention",
              "employee", "hr", "turnover"],
    "forecasting": ["forecast", "demand", "predict", "trend", "inventory",
                    "stockout", "future"],
}

# Output format keywords
OUTPUT_KEYWORDS = {
    "text": ["summarize", "explain", "tell me", "what is", "describe"],
    "charts": ["visualize", "show", "plot", "graph", "chart", "display"],
    "report": ["report", "document", "export", "pdf", "send", "generate"],
}
DEFAULT_OUTPUT_FORMAT = "report"

# Output
OUTPUTS_DIR = Path(__file__).parent / "outputs"
PDF_BRAND_NAME = "Multi-Agentic AI for Business Intelligence"
PDF_FOOTER = "Generated by Multi-Agentic AI for Business Intelligence"
PDF_ACCENT_COLOR = (99, 102, 241)   # indigo RGB for ReportLab
PDF_HEADER_COLOR = (15, 23, 42)     # slate-900

# Demo datasets
DEMO_DATASETS = ["Sales", "HR", "Marketing", "Pricing",
                 "Demand", "Employee Satisfaction"]

# Anomaly detection
ZSCORE_THRESHOLD = 2.5
TOP_N_DEFAULT = 5
FORECAST_DAYS = [30, 60, 90]
CONFIDENCE_INTERVAL_MULTIPLIER = 1.5
CHURN_SATISFACTION_THRESHOLD_LOW = 3
CHURN_SATISFACTION_THRESHOLD_HIGH = 4
CHURN_RETENTION_COST_MULTIPLIER = 0.5
DISCOUNT_SCENARIOS = [0.05, 0.10, 0.15, 0.20]
